name: SeamlessFlight
main: me.asofold.bpl.seamlessflight.SeamlessFlight
version: 1.1.1
softdepend:
- NoCheatPlus

commands:
  seamlessflight:
    aliases:
    - fly
    - sfly
    description: 'Enable or disable flying. Use sfreload to reload the configuration.'
    usage: '/<command> on | /<command> off'
  sfreload:
    description: 'Reload the configuration of SeamlessFlight.'
    usage: '/<command>'

